### ISSUE TITLE
Code review before exam

### ISSUE THREAD

**Issue by menoudyann** [CPNV-RIA1/cadavrexski#15]
Bonjour @NicolasGlassey,

Serait-ce possible d'avoir un petit retour sur notre code (particulièrement les tests) avant le rendu de mercredi ?

Meilleures salutations

**Comment by NicolasGlassey** [comment]
@menoudyann  Bonjour Yann,

J'avoue ne pas y arriver en si peu de temps. Je dois également veiller à ne pas produire d'injustice avec les autres équipes. 

Ne vous inquiètez pas, nous avons détecté la problèmatique de l'architecture bien en amont... si vous avez réussi à tester votre solution, cela semble confirmer que vous avez fait les modifications nécessaires (sinon il aura été impossible de tester).

A demain !
